### ISSUE TITLE
Add the `Shuffle = True` option

### ISSUE THREAD

**Issue by agentzh** [orinc/testml-fan#22]
we can have a shuffle option in the testml code section. In many cases we want to shuffle the order of execution of the test blocks but still keep the original block order for inter-block references (like `--- ^foo`).

**Comment by ingydotnet** [comment]
This will work well because `^foo` references are resolved at compile time and
shuffling will happen at run time. The global var `Shuffle` will be silently
ignored by TestML frameworks without Shuffle support. This is how all the
"special" variables work, like `Diff` and `Plan`.

**Comment by ingydotnet** [comment]
Done in d67866c
